### ISSUE TITLE
Instance not closing properly

### ISSUE THREAD

**Issue by traetox** [chzyer/readline#1]
Instance doesn't appear to be closing properly.  When I attempt to close the instance it returns "errno 0" and doesn't release the terminal.  Attached is a simple application which demonstrates the issue:

```
package main

import (
	"fmt"

	"github.com/chzyer/readline"
)

func main() {
	rl, err := readline.NewEx(&readline.Config{
		Prompt: "rl# ",
	})
	if err != nil {
		fmt.Printf("Failed to create readline: %v\n", err)
		return
	}
	fmt.Printf("enter 2 lines of stuff\n")
	for i := 0; i < 2; i++ {
		line, err := rl.Readline()
		if err != nil {
			fmt.Printf("ERR: %v\n", err)
			return
		}
		fmt.Fprintf(rl.Stderr(), "you said: %v\n", line)
	}
	if err := rl.Close(); err != nil {
		fmt.Printf("Failed to close readline instance: %v\n", err);
	}

	var input string
	if _, err := fmt.Scanf("Input stuff: %s", &input); err != nil {
		fmt.Printf("simple input: %v\n", input)
	}
}
```

After attempting to close (I can attempt to close a few times, 2nd one seems to not return an error) the readline Instance is still consuming input.  If I am not using it correctly, let me know.

**Comment by chzyer** [comment]
@traetox , Thanks for catch that!

**Comment by chzyer** [comment]
Fixed! Please reopen if it still not working.
