### ISSUE TITLE
Dynamic autocomplete for multiple args

### ISSUE THREAD

**Issue by rhtyd** [chzyer/readline#139]
I've a API/command I'm trying to support, for example:
```
(local) 🐵 > list users 
account=      domainid=     id=           keyword=      page=         state=        
accounttype=  filter=       isrecursive=  listall=      pagesize=     username=  
```

However, this can take multiple options such as `id=` and `state=` etc. However, I would also like to provide auto-completion for the args, for example when user type tab-tab on `id=`, this might require calling a HTTP api to get args/params for this for example `one, two, three`. However, when `id=value` is completed the dynamic auto-completion method fails to show the returned `[]string`.

**Comment by chzyer** [comment]
It sounds great ~

**Comment by rhtyd** [comment]
@chzyer thanks, I was expecting some docs on writing our own completion. Can you help?

**Comment by rhtyd** [comment]
Closing, figured out a way though it would be great to have a high level method/function instead;
https://github.com/apache/cloudstack-cloudmonkey/blob/master/cli/completer.go
