### ISSUE TITLE
Re-render hook for asynchronous display

### ISSUE THREAD

**Issue by t-bast** [chzyer/readline#140]
Hello, first of all thanks for the good work on this package!

I'm using readline but with an asynchronous event loop that will print messages to the console at unknown times. Printing works correctly, but it makes the prompt prefix (">") disappear until the user enters a key stroke. Is there a way to force a re-render of the prompt and its current buffer after my asynchronous message was displayed?

I tried raising a SIGWINCH signal hoping it would trigger a re-render (I think it should) but it doesn't.
Is there another way, or is it possible to add a way to do that?

Thanks!

**Comment by maxlandon** [comment]
Hello @t-bast,
I have exactly the same problem you describe here, but I've been knocking my head on the table for days trying to resolve this ! (Ma tête va finir par céder si la solution ne tombe pas).

A bit of context: 
My client is waiting for log events from a server (among other kinds of messages), via a handler type such as the EventsHandler below. (I pass to it a Session object, which is basically my readline instance + a few things).
My handler enters in a for loop such as this one:

```go
var logEventRequests = make(chan map[string]string, 1)

type EventsHandler struct {
        *logrus.Logger
}

func NewEventsHandler(sess *Session) *EventsHandler {
            handler := &EventsHandler{logrus.New(),}
            
            go handler.handleEvents(sess)

            return handler
}

func (e *EventsHandler) handleEvents(sess *Session) {
        for  {
                  event := <- logEventRequests:
                  switch event["level"] {
                         case "debug":
                                 fmt.Println("new debug log arrived")
                         case "info":
                                 fmt.Println("new log info arrived)
                  }
        }
}
```
My issue is the following: The events will be correctly printed at the screen, but there is no way  to get back control of the shell (no prompt, no input, nothing. I have to ^C to quit). I guess my issue is related to the way I manage the loop, which is wrong, but I cannot find the solution.
I have tried adding `sess.shell.Refresh()` statements in the for loop, but nothing works.


If you had found the solution for this, I will be immensely grateful. I could pay the beer !

**Comment by t-bast** [comment]
Closing this issue as the repo doesn't seem to be maintained.
