### ISSUE TITLE
Completer fault

### ISSUE THREAD

**Issue by michalpristas** [chzyer/readline#15]
Hi I noticed a malfunction when having PcItems with same prefix
Using this completer:
```{go}
var completer = readline.NewPrefixCompleter(
		readline.PcItem("simple",
			readline.PcItem("rule",
				readline.PcItem("-name"),
				readline.PcItem("-name2"),
				readline.PcItem("-name23"),
			),
		),
	)
```
A will get following completion tree
.simple
......rule
............-name (as it is common prefix for all)
..................-name-name (this is not so good)
..................-name2
..................-name23

I would look at it on my own but I'm not sure where to look.
it works fine for 
var completer = readline.NewPrefixCompleter(
		readline.PcItem("simple",
			readline.PcItem("rule",
				readline.PcItem("-abc"),
				readline.PcItem("-def"),
				readline.PcItem("-qwe"),
			),
		),
	)

prefix of agrs is not common

**Comment by chzyer** [comment]
I think it may cause by `PrefixCompleter`. I will check it later :)

**Comment by michalpristas** [comment]
thanks a lot

**Comment by chzyer** [comment]
@michalpristas Fixed. Please check that commit above.
