### ISSUE TITLE
Checking password strength

### ISSUE THREAD

**Issue by sahib** [chzyer/readline#16]
Hello @chzyer, thanks for this nifty library.

I hit a little problem when using it though: I want a user to enter a password (in plaintext) and check it's strength using the [zxcvbn](https://github.com/nbutton23/zxcvbn-go) library. Depending on the strength I would color the ``Password: `` prompt in a friendlier color. For this I modified the ``Autorefresh`` example of yours, so that the refresh would fetch the current input, check the strength and do a fitting ``SetPrompt()``.

However, when using ``rl.Operation.Runes()`` directly all sort of weird behaviour appears.
This appears due to the fact that it does not only fetch the current runes, but also [does some IO](https://github.com/chzyer/readline/blob/master/operation.go#L256). For testing I exposed the ``buf *RuneBuffer`` in ``readline.Operation`` to the outside and used it's ``Runes()`` method directly.

Despite being an awful hack, it seems to work - am I doing something awfully wrong, or would the addition of another method that just fetches the current buffer contents appropiate?

Here's my current (working) attempt:
https://gist.github.com/sahib/2ee21e8d636c98876a83

Thanks.

**Comment by chzyer** [comment]
Hi, @sahib 
Your idea is so cool~ I would like to support for it ASAP(maybe I will write a example based your idea).

**Comment by sahib** [comment]
Cool! Tell me if I should help out with something (e.g. with a PR).

**Comment by chzyer** [comment]
Hi, @sahib 
I just update the [example](https://github.com/chzyer/readline/blob/839c0013a8e2558c2ecacf3bd0505f5223182fee/example/main.go#L100-L104), you can check the `setpassword` part.
I added some API (e.g. ReadPasswordWithConfig), it provided a new user experience for entering password which we can see passwords by mask chars, even we can modify it.  

**HOW IT WORKS**  
1. I added a new field `Listener` for `Config`, `readline` will pass any keys which pressed to it, so we can be aware of what password now.
2. `readline` supports change `Config` in anytime by calling `SetConfig`, so it can provide a different behavior while entering password(disable history, adding a mask etc).
3. Restore the default config after we finish reading password.

Have a try! Close this issue if that was enough for you, and then I will release a new version :)

**Comment by sahib** [comment]
Great! 

This works perfectly fine for me and is cleaner than the previous polling approach
and is more generally useful at the same time.

Here is my updated usecase: https://gist.github.com/sahib/2ee21e8d636c98876a83

All problems resolved. Thanks!

**Comment by chzyer** [comment]
@sahib, Your demo is great!
Would you mind to send a PR that add it into `example/pass_strength/pass_strength.go` and write some copyright about it on the head of source file? That would be great!

**Comment by sahib** [comment]
@chzyer: Done, see PR https://github.com/chzyer/readline/pull/18.
