### ISSUE TITLE
History buf

### ISSUE THREAD

**Issue by michalpristas** [chzyer/readline#19]
Sometimes when I use history using up/down arrows the output get broken.
Command is printed out but not to current line. 
It will get printed to a new line and I will get another line for input. Hard to explain hard to reproduce. 

Example will be the best:

For expected history
command one
command two
command three
command four

Initial state (enter command is propmt message, _ is current cursos):
enter command: _

after playing with history I got output like this
enter command: command three _

(after pressing up arrow)

enter command: 
command two
_

(then I press up arrow again [enter key is not pressed] and output is like this)

enter command: 
command two
enter command: command one _

I hope it is a bit clear with this example. I'm not really sure where to look at

**Comment by chzyer** [comment]
Hi, @michalpristas 
Sorry for reply so late, I've been very busy recently.
What's the content of your history file(`/tmp/readline.tmp`)? Is that correct?
It seems that `command two` has a `\n` tailer.

Anyway, I can't reproduce your example. And according to your example, how is `enter command: _` become `enter command: command three _` ? Where is the `command four` ?

**Comment by michalpristas** [comment]
Hi @chzyer 
I got time to investigate the issue and I found out it is not as random as it seemed to me.

the guaranteed way to reproduce this issue is:

###1. use this completer
var completer = readline.NewPrefixCompleter(	
	readline.PcItem("os",
		readline.PcItem("houseofcards"),
		readline.PcItem("card")
)

###2. go run
###3 enter command: os houseofcards, press enter
###4 press this combo of keys
1 x up arrow (os houseofcards get displayed)
13x backspace (only thing left is: "os ")
1x 'c' (now you got 'os c'
1x tab card get completed
1x enter, command is executed

###5 Press up arrow 2 times and you will see something bad
such as:
>> os card
fcards

I tried to look at the code but it changed a bit so I got lost :-)

**Comment by chzyer** [comment]
Thanks for the investigation. That's so cool that it reproduce everytime~ I will fix it ASAP

**Comment by michalpristas** [comment]
thanks for prompt response, looking forward
