### ISSUE TITLE
unrecognized import path "golang.org/x/crypto/ssh/terminal"

### ISSUE THREAD

**Issue by ije** [chzyer/readline#20]
when i try to install readline package by `go get`, there is an error print: `unrecognized import path "golang.org/x/crypto/ssh/terminal"`

**Comment by chzyer** [comment]
`readline` is depend on package `golang.org/x/crypto/ssh/terminal`. 
But I have been try `go get github.com/chzyer/readline` or `go get gopkg.in/readline.v1`, and they both download `golang.org/x/crypto/ssh/terminal` if it's not exists.
Anyway, I think `go get golang.org/x/crypto/ssh/terminal` will works.

**Comment by ije** [comment]
sorry, maybe it's the network problem. because i living in China... I'm trying to download terminal package manually
