### ISSUE TITLE
screen clears when starting

### ISSUE THREAD

**Issue by sigmonsays** [chzyer/readline#3]
I'm running the simplest example under screen and the terminal is getting cleared at startup. It shouldn't be clearing the screen.

If I capture a screen log I get the following
<pre>
$ hexdump -C screenlog.14
00000000  67 6f 20 72 75 6e 20 74  65 73 74 2e 67 6f 20 0d  |go run test.go .|
00000010  0a 1b 5b 4a 1b 5b 32 4b  0d 08 1b 5b 32 4b 0d 08  |..[J.[2K...[2K..|
00000020  1b 5b 32 4b 0d 08 1b 5b  32 4b 0d 08 1b 5b 32 4b  |.[2K...[2K...[2K|
00000030  0d 08 1b 5b 32 4b 0d 08  1b 5b 32 4b 0d 08 1b 5b  |...[2K...[2K...[|
00000040  32 4b 0d 08 1b 5b 32 4b  0d 08 1b 5b 32 4b 0d 08  |2K...[2K...[2K..|
00000050  1b 5b 32 4b 0d 08 1b 5b  32 4b 0d 08 1b 5b 32 4b  |.[2K...[2K...[2K|
00000060  0d 08 1b 5b 32 4b 0d 08  1b 5b 32 4b 0d 08 1b 5b  |...[2K...[2K...[|
00000070  32 4b 0d 08 1b 5b 32 4b  0d 08 1b 5b 32 4b 0d 08  |2K...[2K...[2K..|
00000080  1b 5b 32 4b 0d 08 1b 5b  32 4b 0d 08 1b 5b 32 4b  |.[2K...[2K...[2K|
00000090  0d 08 1b 5b 32 4b 0d 08  1b 5b 32 4b 0d 08 1b 5b  |...[2K...[2K...[|
000000a0  32 4b 0d 08 1b 5b 32 4b  0d 08 1b 5b 32 4b 0d 08  |2K...[2K...[2K..|
000000b0  1b 5b 32 4b 0d 08 1b 5b  32 4b 0d 08 1b 5b 32 4b  |.[2K...[2K...[2K|
000000c0  0d 08 1b 5b 32 4b 0d 08  1b 5b 32 4b 0d 08 1b 5b  |...[2K...[2K...[|
000000d0  32 4b 0d 08 1b 5b 32 4b  0d 08 1b 5b 32 4b 0d 08  |2K...[2K...[2K..|
000000e0  1b 5b 32 4b 0d 08 1b 5b  32 4b 0d 08 1b 5b 32 4b  |.[2K...[2K...[2K|
000000f0  0d 08 1b 5b 32 4b 0d 08  1b 5b 32 4b 0d 08 1b 5b  |...[2K...[2K...[|
00000100  32 4b 0d 08 1b 5b 32 4b  0d 08 1b 5b 32 4b 0d 08  |2K...[2K...[2K..|
00000110  1b 5b 32 4b 0d 08 1b 5b  32 4b 0d 08 1b 5b 32 4b  |.[2K...[2K...[2K|
00000120  0d 08 1b 5b 32 4b 0d 08  1b 5b 32 4b 0d 08 1b 5b  |...[2K...[2K...[|
00000130  32 4b 0d 08 1b 5b 32 4b  0d 08 1b 5b 32 4b 0d 08  |2K...[2K...[2K..|
00000140  1b 5b 32 4b 0d 08 1b 5b  32 4b 0d 08 1b 5b 32 4b  |.[2K...[2K...[2K|
00000150  0d 08 1b 5b 32 4b 0d 08  1b 5b 32 4b 0d 08 1b 5b  |...[2K...[2K...[|
00000160  32 4b 0d 08 1b 5b 32 4b  0d 08 1b 5b 32 4b 0d 08  |2K...[2K...[2K..|
00000170  1b 5b 32 4b 0d 08 1b 5b  32 4b 0d 08 1b 5b 32 4b  |.[2K...[2K...[2K|
00000180  0d 08 1b 5b 32 4b 0d 08  1b 5b 32 4b 0d 08 1b 5b  |...[2K...[2K...[|
00000190  32 4b 0d 08 1b 5b 32 4b  0d 08 1b 5b 32 4b 0d 08  |2K...[2K...[2K..|
000001a0  1b 5b 32 4b 0d 08 1b 5b  32 4b 0d 08 1b 5b 32 4b  |.[2K...[2K...[2K|
000001b0  0d 08 1b 5b 32 4b 0d 08  1b 5b 32 4b 0d 08 1b 5b  |...[2K...[2K...[|
000001c0  32 4b 0d 08 1b 5b 32 4b  0d 08 1b 5b 32 4b 0d 08  |2K...[2K...[2K..|
000001d0  1b 5b 32 4b 0d 08 1b 5b  32 4b 0d 08 1b 5b 32 4b  |.[2K...[2K...[2K|
000001e0  0d 08 1b 5b 32 4b 0d 08  1b 5b 32 4b 0d 08 1b 5b  |...[2K...[2K...[|
000001f0  32 4b 0d 08 1b 5b 32 4b  0d 08 1b 5b 32 4b 0d 08  |2K...[2K...[2K..|
00000200  1b 5b 32 4b 0d 08 1b 5b  32 4b 0d 08 1b 5b 32 4b  |.[2K...[2K...[2K|
00000210  0d 08 1b 5b 32 4b 0d 08  1b 5b 32 4b 0d 08 1b 5b  |...[2K...[2K...[|
00000220  32 4b 0d 08 1b 5b 32 4b  0d 08 1b 5b 32 4b 0d 08  |2K...[2K...[2K..|
00000230  1b 5b 32 4b 0d 08 1b 5b  32 4b 0d 08 1b 5b 32 4b  |.[2K...[2K...[2K|
00000240  0d 08 1b 5b 32 4b 0d 08  1b 5b 32 4b 0d 08 1b 5b  |...[2K...[2K...[|
00000250  32 4b 0d 08 1b 5b 32 4b  0d 08 1b 5b 32 4b 0d 08  |2K...[2K...[2K..|
00000260  1b 5b 32 4b 0d 08 1b 5b  32 4b 0d 08 1b 5b 32 4b  |.[2K...[2K...[2K|
00000270  0d 08 3e 20                                       |..> |
</pre>

take the simplest example code from the main github page
<pre>
package main

import "github.com/chzyer/readline"

func main() {

        rl, err := readline.New("> ")
        if err != nil {
                panic(err)
        }
        defer rl.Close()

        for {
                line, err := rl.Readline()
                if err != nil { // io.EOF
                        break
                }
                println(line)
        }
}

</pre>

**Comment by chzyer** [comment]
@sigmonsays, Hi~
I can't reproduce this in my environment.
Which OS and terminal emulator you test with? What's the value of $TERM?
Thanks.

**Comment by chzyer** [comment]
@sigmonsays , I think I can reproduce it in `screen`.

**Comment by chzyer** [comment]
Fixed. Please reopen this issue if it still not working. :)

**Comment by sigmonsays** [comment]
works perfectly. Thanks!
