### ISSUE TITLE
gopkg does not work with sub-packages

### ISSUE THREAD

**Issue by alecthomas** [chzyer/readline#43]
This is not an issue with readline itself, but impacts uses of it via gopkg. See https://github.com/niemeyer/gopkg/issues/9 for details.

Basically, gopkg only works correctly with single-package repositories. Because `gopokg.in/chzyer/readline.v1` imports `github.com/chzyer/readline/runes`, both repositories will be pulled in, but the latter be at HEAD on master.

I don't have a solution to this unfortunately, I just noticed it when pulling in readline via otto.

**Comment by chzyer** [comment]
Thanks for the notice. 
It seems the only way is remove the "runes" sub package to readline, but that isn't backward compatible. 
So I will copy runes to readline, remove the reference to runes and keep the runes package.
