### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by binary132** [chzyer/readline#5]
Is there a timeline or ETA for Windows support?

**Comment by chzyer** [comment]
@binary132 . Sorry for that I can't promise that when can I finish supporting Windows, but I'm working on it now. There are some features/shortcuts not supported in windows terminal.
Once I done, I will close this issue and let you know :)
Thanks for you attention!

**Comment by chzyer** [comment]
@binary132 , Supporting windows is done, supports all the features which unix has. :)
