### ISSUE TITLE
"Home" and "End" keys not working

### ISSUE THREAD

**Issue by tiago4orion** [chzyer/readline#59]
As documented in the Changelog this features was supposed to be implemented in https://github.com/chzyer/readline/pull/12 but I don't see any code handling HOME and END (only DEL in this PR).

Does HOME and END works for anyone?

**Comment by chzyer** [comment]
BTW, It works by `fn` + `<left>` on my mac.

**Comment by tiago4orion** [comment]
I'm using a DELL keyboard and pressing HOME emits the characters OH and pressing END emits OF in the console.

This is the expected behaviour?

I'm using arch linux.

**Comment by chzyer** [comment]
I thinks the commit above will fix that :)
Please reopen if it is still not working

**Comment by tiago4orion** [comment]
It works!
Thank you!
