### ISSUE TITLE
No carriage return after command line

### ISSUE THREAD

**Issue by setnicka** [chzyer/readline#62]
When autocompleting or after completing command (after hitting enter), the next line after command line is indented. It starts on the same position as the old one ends, ilustration:
```
» say 
      hello   bye 
```
or
```
» test test
           2016/07/21 09:55:19 you said: "test test"

```

Tested on two Linux machines, one of them was Debian 5.4.0-6 (Linux version 4.6.0-1-amd64) with pure installation of Go:
```
sudo apt install golang
export GOPATH=$HOME/go
go get github.com/chzyer/readline
go run go/src/github.com/chzyer/readline/example/readline-demo/readline-demo.go
```

This bug is probably caused by some changes in external packages, because when I was using older version of all packages (e.q. one month), all works as expected.

**Comment by chzyer** [comment]
Is this works?
```{shell}
$ go install github.com/chzyer/readline/example/readline-demo
$ $GOBIN/readline-demo
```

**Comment by chzyer** [comment]
@setnicka Thanks, I can reproduce it!

**Comment by setnicka** [comment]
@chzyer Tested, it is probably caused by this commit in golang/crypto:
https://github.com/golang/crypto/commit/911fafb28f4ee7c7bd483539a6c96190bbbccc3f

When I manually reverted it the readline behaves as it should. So it is something around setting terminal flags.

**Comment by chzyer** [comment]
@setnicka Awesome! I will figure out how to fix it.

**Comment by chzyer** [comment]
It should be fixed via that pr.
This is really a big problem, your issue is deeply appreciated!
