### ISSUE TITLE
Tab-selection of completions looks wrong when options span multiple lines

### ISSUE THREAD

**Issue by aktungmak** [chzyer/readline#63]
If the suggested completions are long enough to take up more than one terminal line, pressing tab to move the highlight causes more lines to be printed. Here some example code:

```go
package main

import "github.com/chzyer/readline"

var completer = readline.NewPrefixCompleter(
	readline.PcItem("all_these_options"),
	readline.PcItem("take_up_more_than"),
	readline.PcItem("one_terminal_line"),
	readline.PcItem("so_the_highlights"),
	readline.PcItem("do_not_work_right"))

func main() {
	rl, err := readline.NewEx(&readline.Config{
		Prompt:       "> ",
		AutoComplete: completer,
	})
	if err != nil {
		panic(err)
	}
	defer rl.Close()

	for {
		line, err := rl.Readline()
		if err != nil {
			break
		}
		println(line)
	}
}
```
If I run this snippet and press `Tab` five times, this is what I see:
![result](https://cloud.githubusercontent.com/assets/10996135/17018192/edcc7328-4f36-11e6-9f3d-8d532f3cb43c.PNG)

It looks like only the current line is being redrawn, and since there are two lines drawn it keeps moving down each time. The re-draw process should redraw all the lines, not just the last.
With shorter option texts, this doesn't happen.

This definitely happens in a windows 7 command prompt, I haven't tried it out on any other terminals yet.

**Comment by setnicka** [comment]
I think it may be caused by the same problem as #62

**Comment by aktungmak** [comment]
ok, I will pull the fix for #62 and test again

**Comment by aktungmak** [comment]
I just pulled the latest revision (4f0ff8f850e0dcfd6993a35f3ed3af9bd9e18602) and rebuild, but unfortunately I am still seeing the same behavior :(

**Comment by chzyer** [comment]
@aktungmak 
I just fix some bug on windows (f83f326).   
But (4f0ff8f) should can't seeing the same behavior. Have you try `go install github.com/chzyer/readline` to rebuild the package?
I tested in Windows7, and it works well.
So, I'm looking forward your new testing result :)

There is something strangely:
The behavior of `golang.org/x/crypto/ssh/terminal` didn't changed in windows.

**Comment by chzyer** [comment]
@aktungmak 
I can reproduce your situation now. I'm trying to fix it.

**Comment by chzyer** [comment]
@aktungmak (dc578a1) should fix this.

**Comment by aktungmak** [comment]
tested and its working for me too, thanks!
