### ISSUE TITLE
How can I enable Tab key as input

### ISSUE THREAD

**Issue by kuangchanglang** [chzyer/readline#73]
hi, I'm using readline to accomplish [goshell](https://github.com/kuangchanglang/goshell). And I expect tab key as normal input in any editor, how can I do that?

**Comment by chzyer** [comment]
Hi, tab key is expected to fire autocompletation by default. It's not implemented as inserting a tab character yet, but it's possible to implement a 'AutoCompleter' to fill 4 spaces. Is that meet your demand?

**Comment by chzyer** [comment]
@kuangchanglang 
You can give the latest version a try :)
It's enabled by default now.

**Comment by kuangchanglang** [comment]
@chzyer Thank you very much, it works fine for me now.
