### ISSUE TITLE
Panic on windows when completing

### ISSUE THREAD

**Issue by ktye** [chzyer/readline#8]
You simple example wrapped into a binary panics on windows, when pressing the tab key.
This happens on windows 7 and windows 8.1.

package main

import "github.com/chzyer/readline"

func main() {
        rl, err := readline.New("> ")
        if err != nil {
                panic(err)
        }
        defer rl.Close()

        for {
                line, err := rl.Readline()
                if err != nil { // io.EOF
                        break
                }
                println(line)
        }

}

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x43d363]

goroutine 8 [running]:
github.com/chzyer/readline.(*opCompleter).OnComplete(0xc082050000)
	c:/test/go/src/github.com/chzyer/readline/complete.go:76 +0x2e3
github.com/chzyer/readline.(*Operation).ioloop(0xc082008280)
	c:/test/go/src/github.com/chzyer/readline/operation.go:118 +0x877
created by github.com/chzyer/readline.NewOperation
	c:/test/go/src/github.com/chzyer/readline/operation.go:64 +0x491

goroutine 1 [chan receive]:
github.com/chzyer/readline.(*Operation).Runes(0xc082008280, 0x0, 0x0, 0x0, 0x0, 0x0)
	c:/test/go/src/github.com/chzyer/readline/operation.go:258 +0xbe
github.com/chzyer/readline.(*Operation).String(0xc082008280, 0x0, 0x0, 0x0, 0x0)
	c:/test/go/src/github.com/chzyer/readline/operation.go:248 +0x56
github.com/chzyer/readline.(*Instance).Readline(0xc08200a410, 0x0, 0x0, 0x0, 0x0)
	c:/test/go/src/github.com/chzyer/readline/readline.go:76 +0x57
main.main()
	c:/test/go/src/rltest/main.go:13 +0xaf

goroutine 5 [chan receive]:
github.com/chzyer/readline.(*ANSIWriter).ioloop(0xc0820041c0)
	c:/test/go/src/github.com/chzyer/readline/ansi_windows.go:101 +0x139
created by github.com/chzyer/readline.NewANSIWriter
	c:/test/go/src/github.com/chzyer/readline/ansi_windows.go:64 +0xd7

goroutine 6 [chan receive]:
github.com/chzyer/readline.(*ANSIWriter).ioloop(0xc082004240)
	c:/test/go/src/github.com/chzyer/readline/ansi_windows.go:101 +0x139
created by github.com/chzyer/readline.NewANSIWriter
	c:/test/go/src/github.com/chzyer/readline/ansi_windows.go:64 +0xd7

goroutine 7 [syscall, locked to thread]:
github.com/chzyer/readline.func·021(0xc0820069a0, 0x4, 0x4, 0x0, 0x0)
	c:/test/go/src/github.com/chzyer/readline/windows_api.go:120 +0x40b
github.com/chzyer/readline.(*RawReader).Read(0xc08200a3d0, 0xc08205b000, 0x1000, 0x1000, 0x4, 0x0, 0x0)
	c:/test/go/src/github.com/chzyer/readline/rawreader_windows.go:46 +0x131
bufio.(*Reader).fill(0xc082042480)
	c:/go/src/bufio/bufio.go:97 +0x1d5
bufio.(*Reader).ReadRune(0xc082042480, 0xc082042300, 0xc082049f14, 0x0, 0x0)
	c:/go/src/bufio/bufio.go:227 +0xde
github.com/chzyer/readline.(*Terminal).ioloop(0xc082008230)
	c:/test/go/src/github.com/chzyer/readline/terminal.go:95 +0x1c3
created by github.com/chzyer/readline.NewTerminal
	c:/test/go/src/github.com/chzyer/readline/terminal.go:39 +0x279
exit status 2

**Comment by chzyer** [comment]
@ktye Thanks for catch that! It's fixed now.
