### ISSUE TITLE
feature request: case-insensitive history

### ISSUE THREAD

**Issue by knz** [chzyer/readline#84]
in CockroachDB if a user enters "SELECT" ... it would be nice to be able to do Ctrl+R then "sel..." in lowercase and see the SELECT come back from history.

Currently the history search is case sensitive so this does not work.

Ideally the behavior would be configurable.

**Comment by chzyer** [comment]
Hi, this would be done at this weekend.

**Comment by chzyer** [comment]
@knz 
Set `HistorySearchFold` to true in `readline.Config` to open this feature :)

**Comment by knz** [comment]
It works now! Thank you so much.
