### ISSUE TITLE
liner compatibility

### ISSUE THREAD

**Issue by ktye** [chzyer/readline#9]
It would be nice to be compatible with liner, at least for the basic usages.
One idea is, to create a subpackage:
github.com/chzyer/readline/liner
which translates the liner interface to readline.
In this case, only the import path needs to be changed and it's very easy to compare the libraries.

What do you think?

**Comment by chzyer** [comment]
I think both `liner` and `readline` only provide a few interfaces, it's not too hard or too many codes to modified.   
Maybe wrapping interfaces to liner it goes too far?
