### ISSUE TITLE
Readline doesn't compile on Solaris

### ISSUE THREAD

**Issue by mitchellh** [chzyer/readline#95]
We're gearing up to use this library for [Terraform](https://github.com/hashicorp/terraform) and we target Solaris and have users using that OS. This library unfortunately doesn't compile there due to missing the `State` struct there.

We've built around it with build tags for now to simply not support our interactive console feature there but it'd be fantastic if this was supported.

**Comment by chzyer** [comment]
@mitchellh , noted!
terraform is awesome! I will try to support Solaris.

**Comment by mitchellh** [comment]
Thanks @chzyer. If you want to see what we're doing: https://github.com/hashicorp/terraform/pull/10093 

It'd be great to support Solaris. :) I'm impressed with the support for all the other operating systems you did a fantastic job here.

**Comment by mitchellh** [comment]
Awesome thanks!
